version: "3.8"
services:
  project-template-api:
    container_name: project-template-api
    hostname: project-template-api
    build:
      context: ./
      dockerfile: ./docker-files/api.Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      MONGO_CONNECTION_URL: "${MONGO_CONNECTION_URL}"
      PASSWORD_HASH_SALT_ROUNDS: ${PASSWORD_HASH_SALT_ROUNDS}
      AUTHENTICATION_SECRET: "${AUTHENTICATION_SECRET}"
    networks:
      - project-template
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  project-template:
    name: "project-template"
    driver: bridge
