"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    ALREADY_REGISTERED_USER: "ALREADY_REGISTERED_USER",
    INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
    WITHOUT_AUTHORIZATION: "WITHOUT_AUTHORIZATION",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    NOT_FOUND: "NOT_FOUND",
    NOT_FOUND_USER: "NOT_FOUND_USER",
    NOT_FOUND_MISSION: "NOT_FOUND_MISSION",
    CANNOT_ACCEPT_OWN_MISSION: "CANNOT_ACCEPT_OWN_MISSION",
    CANNOT_COMPLETE_ANOTHER_USERS_MISSION: "CANNOT_COMPLETE_ANOTHER_USERS_MISSION",
    ALREADY_ACCEPTED_MISSION: "ALREADY_ACCEPTED_MISSION",
    ALREADY_COMPLETED_MISSION: "ALREADY_COMPLETED_MISSION",
    MISSION_NOT_IN_PROGRESS: "MISSION_NOT_IN_PROGRESS",
    CANNOT_CANCEL_ANOTHER_USER_MISSION: "CANNOT_CANCEL_ANOTHER_USER_MISSION",
    ALREADY_CANCELED_MISSION: "ALREADY_CANCELED_MISSION",
    CANNOT_UNBIND_ANOTHER_USER_MISSION: "CANNOT_UNBIND_ANOTHER_USER_MISSION",
    YOU_NOT_IN_THIS_MISSION: "YOU_NOT_IN_THIS_MISSION",
    ALREADY_ADDED_USER: "ALREADY_ADDED_USER",
};
