export default {
  ALREADY_REGISTERED_USER: "ALREADY_REGISTERED_USER",
  INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  WITHOUT_AUTHORIZATION: "WITHOUT_AUTHORIZATION",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  NOT_FOUND_USER: "NOT_FOUND_USER",
  ALREADY_ADDED_USER: "ALREADY_ADDED_USER",
};
